### ISSUE TITLE
Login might fail if version can't be retrieved via API

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/Mediawiki-Japi#32]
error code=readapidenied info:'You need read permission to use this module'

Stacktrace

java.lang.Exception: error code=readapidenied info:'You need read permission to use this module'
	at com.bitplan.mediawiki.japi.MediaWikiApiImpl.handleError(MediaWikiApiImpl.java:93)
	at com.bitplan.mediawiki.japi.MediaWikiApiImpl.fromXML(MediaWikiApiImpl.java:146)
	at com.bitplan.mediawiki.japi.Mediawiki.getActionResult(Mediawiki.java:409)
	at com.bitplan.mediawiki.japi.Mediawiki.getQueryResult(Mediawiki.java:434)
	at com.bitplan.mediawiki.japi.Mediawiki.getSiteInfo(Mediawiki.java:464)
	at com.bitplan.mediawiki.japi.MediaWikiApiImpl.getVersion(MediaWikiApiImpl.java:208)
	at com.bitplan.mediawiki.japi.Mediawiki.prepareLogin(Mediawiki.java:494)
	at com.bitplan.mediawiki.japi.Mediawiki.login(Mediawiki.java:547)

**Comment by WolfgangFahl** [comment]
The 2016 workaround is hurting even more with 1.33 up
